version: '3.8'

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.115.0
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - ./data/victoria-metrics:/storage

  vmagent:
    image: victoriametrics/vmagent:v1.115.0
    container_name: vmagent
    command:
      - '-promscrape.config=/config/scrape.yml'
      - '-remoteWrite.url=http://victoria-metrics:8428/api/v1/write'
    volumes:
      - ./config:/config:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
